name: network_helper
description: Dart Package to handle all network stuff
version: 0.0.1
author: Johnathan Breshears
homepage: https://github.com/johnathanbreshears/NetworkHelper

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.9
  cookie_jar: 1.0.0
  connectivity: ^0.4.3+7
  ssh: ^0.0.7
  path_provider: ^1.3.0
